README.md

Issue #27 
| *Successfully Added the Steps Required for Contributing to this Repository* |

Added Contribution Steps

---

client/src/components/Footer/Footer.jsx

Issue No : #41
updates year automatically

dynamic footer year

---

CODE_OF_CONDUCT.md

closes #46 
I have added Code of Conduct . Which will give guidelines to the Contributors.

Fixed : issue #46

---

server/config.js
server/controllers/mailer.js
server/controllers/user.controller.js
server/database/db.js
server/index.js
server/middleware/auth.js
server/middleware/errorMiddleware.js
server/package-lock.json
server/utils/config.js

The `config.js`  file is exposed to the root server folder making it vulnerable.
1. The aim of this PR is to Refactor the **SERVER** folder structure, by creating a separate **_Utils_** folder for referencing environment variables.
2. Changing the **_config_** folder name to **_database_** .
Closes: #53 
1. Changed the **config** folder name to **database**.
2. Created a separate **utils** folder for accessing _ENVIRONMENT_VARIABLES_
3. Changed Code into several files which include `(mailer.js , user.controller.js , db.js , middleware/auth.js , middleware/errorMiddleware.js , Index.js)`
To access _ENVIRONMENT_VARIABLES_ go to **utils** folder and add configuration _(eg. OTP: process.env.OTP || "123456")_ and importing to files _(eg. import {Server} from "../utils/config.js")_ and add …

Refactoring "SERVER" folder structure. 

---

client/src/components/About/About.module.css

"Who We Are?" Design Improvement #42
1. The paragraphs in this section are aligned properly to create neat look
2. Gap of right-aligned image is balanced from both side
**Original work**
**Updated work after changes**

Updated Who_We_Are Section

---

client/src/components/Faq/Faq.css
client/src/components/common/Button/Button.module.css

"Contact Us" Section Submit button Alignment #72
1. Submit button alignment in center
2. Alignment of question mark and its corresponding text

Updated "Contact Us" Section

---

client/src/components/Footer/Footer.jsx
client/src/components/Footer/Footer.module.css

Issue Fixed
Closes: #65 
I have fixed the issue and added a link to the mail in the footer section of the website.
I have also added a hover effect to the mail with a link.
| ![Original screenshot](https://user-images.githubusercontent.com/85278243/240720639-774670c0-5953-460a-b78d-1e8ee8b6b702.png) | ![Updated Sceenshot](https://github.com/GrabBits/GrabBits_Website/assets/85278243/1de55ee4-5675-43eb-9ee9-ca7af740dac7) |
Please merge my PR in the main brank under GSSOC'23

Added mail link and hover effect

---

client/src/components/Faq/Faq.css
client/src/components/Faq/Faq.jsx
package-lock.json

#87 
Input tags should be in center in mobile screen
#87
- [+] My code adheres to the established style guidelines of this project.
- [+] I have conducted a self-review of my code.
- [+] I have included comments in areas that may be difficult to understand.
- [+] I have made corresponding updates to the project documentation.
- [+] My changes have not introduced any new warnings.
[scrnli_27_05_2023_21-10-36.webm](https://github.com/GrabBits/GrabBits_Website/assets/92094765/4435c9a9-c634-494a-b6cb-8c78e13670ff)

#87-input tag fix

---

client/src/components/Footer/Footer.module.css

hi @Grab-Bits, i have done the required changes for the footer to make it responsive under issue: #84 
kindly check and merge this under GGSOC 23'

footer changes

---

client/src/components/Extra/Extra.jsx
client/src/components/Extra/Extra.module.css

#56
Added hovering effect and animation on cards of extra section

Adding Hover Effect

---

client/package-lock.json
client/src/components/Faq/Faq.jsx

#78 
Closes: #78 
Hey, @kuvamdazeus I have fixed the toggle button which was wrong in one direction only. I have added a simple if else statement to check wether the toggle button is active or not. For convenience, I have attached the screenshot of the changes made. Have a look at it. Please review my pr and merge it. Thank you!
| ![Screenshot (797)](https://github.com/GrabBits/GrabBits_Website/assets/100675296/4550e562-6421-496b-93ec-04c7f1f77055) | ![Screenshot (796)](https://github.com/GrabBits/GrabBits_Website/assets/100675296/a81c0a3e-b836-467f-80d6-28ac467386dd) |

Fixed toggle button

---

README.md

added tech stacks

---

client/src/components/Opportunities/Opportunities.jsx
client/src/components/Opportunities/Opportunities.module.css

#92
To handle this issue just make a parent div for search bar and add media query to it.
https://github.com/GrabBits/GrabBits_Website/assets/97789487/e4ce879f-8cfa-4e4f-bd4b-6a1fc56c1efc

handling tags dislocation

---

.github/ISSUE_TEMPLATE/Documentation.yml
.github/ISSUE_TEMPLATE/style.yml

*Missing styles and documentation issues in the issue template*
Closes: #83 
*Added the following files for:-*
- Documentation Issue
- Style Issue
**Thank you for giving me this opportunity @kuvamdazeus**

Additions in Issue template done

---

client/src/components/Faq/Faq.jsx

Clicking on a FAQ in FAQs section did not open the dropdown directly. It required clicking on the dropdown arrow icon
Fixes #110 
Now, clicking on each FAQ's header expands the accordian.

Fix FAQ Accordian

---

README.md

Closes: #109
I have appended a contributor graph to the README.md file.

docs: Add Contributor Graph

---

client/src/components/Opportunities/Opportunities.jsx
client/src/helper/debounce.js

#82 
Added a new file named debounce.js under src/helper
Updated Opportunities.jsx and added the debounce to the search field

Add Debounce to Search Field

---

client/package-lock.json
client/package.json
client/src/App.jsx
client/src/components/GoToTop.js

Few pages are long and the user has to scroll up to go to the navbar so for that i have added a Back to Top button. It is a responsive button which will be visible when you are not at top and also adjustable according to the screen size. This is also animated and move up and down in one second.
Closes: #77
- Added a new function to handle Back to top option.
- Added a file in component folder for that.

Add Back To Top Button

---

client/src/components/Navbar/Navbar.jsx

Closes: #126 
https://github.com/GrabBits/GrabBits_Website/assets/77603501/7c5bee8b-87cf-4039-8f2e-2a8a9f0b949b

Fixed bug : redirect to top of page #126

---

.github/pull_request_template.yml

Closes: #142 
Added a PR Template in YML Format

Fixed #142 - PR Template

---

client/src/components/Extra/Extra.module.css

This PR Closes Issue: #125 
- client/src/components/Extra/Extra.module.css
[Grab-Bits.webm](https://github.com/GrabBits/GrabBits_Website/assets/130365071/68d9a685-a28d-4e00-a2f9-14bbbca302ad)
Please review this PR.
Thanks

[Fix]: content overflows out of container on mobile screen devices #125

---

client/src/components/Faq/Faq.jsx

Before fixing the bug I was taking the invalid email. Now it's fixed.  I am GSSOC 2023.
Closes: #[133]
I only change the input tag type to email and for a phone number to telephone. 
https://github.com/GrabBits/GrabBits_Website/assets/90946899/5ebae428-eaee-4a14-8a74-0e91d108109d

[Bug] faq form fix

---

client/src/components/Faq/Faq.jsx

Closes: #157 
Before : 
https://github.com/GrabBits/GrabBits_Website/assets/76463001/93e4e208-dc53-4801-bd9d-20ca68e54e9f
After :
https://github.com/GrabBits/GrabBits_Website/assets/76463001/f6dff1c2-3963-43bf-b7dd-6375bd9e5712

Corrected the bug in the accordion section

---

client/src/components/Extra/Extra.jsx
client/src/components/Footer/Footer.jsx
client/src/components/Landing/Landing.jsx
client/src/components/Testimonials/Testimonial.jsx
client/src/components/common/Ticket/Ticket.jsx

Closes: #168 
Added proper alt attributes to the img tags.

Added alt attributes

---

client/src/App.css
client/src/App.jsx
client/src/components/index.js
client/src/pages/index.js

Closes: #167 
Implemented Lazy loading for all the pages in this project due to which whenever the website loads initially then only the pages that are visible to the user are loaded instead of the whole website. This reduces the initial loading time making the user experience better.

Lazy loading added

---

client/public/index.html

Closes: #187 
Added various meta tags like description, keywords, open graph, etc.

Meta tags added

---

client/src/components/common/Input/Input.module.css
client/src/components/common/Textarea/Textarea.module.css

This PR contains the updated code for the consistent design of contact form on large screens. This PR is the result of the following issue:
Contact Us Form Different Look on Large Screens #194
Closes: #194
Correction of styling in contact form to make it appear same on large screens.
| ![grabbits (1)](https://github.com/GrabBits/GrabBits_Website/assets/115794049/8a4e6a99-faf1-4026-b8de-416a6e3c7873)  | ![grabbit-2nd-pr (2)](https://github.com/GrabBits/GrabBits_Website/assets/115794049/460eafe8-f316-499d-932e-8e95da9b7e72) |

Contact Us Form Different Look on Large Screens Correction

---

.github/workflows/greetings.yml

Closes: #158 
- .github/workflows/greetings.yml
Please review this PR.
Thanks

Fixed GitHub Action workflow for greetings #158

---

client/package-lock.json
client/package.json
client/src/App.css
client/src/App.jsx

Added preloader page to the website under GSSOC 2023. 
@Bhushan8177 
Closes: #155 
Added preloader page to the website for only 2 seconds
| ![Updated screenshot](link) |  
|

Added preloader page issue-155

---

client/src/components/Opportunities/Opportunities.jsx
server/controllers/job.controller.js

pagination fixed

---

client/src/components/Opportunities/Opportunities.jsx
server/controllers/job.controller.js

Reverts GrabBits/GrabBits_Website#201
@vivxsdb

Revert "pagination fixed"

---

client/package-lock.json
client/package.json
client/src/App.css
client/src/App.jsx

Reverts GrabBits/GrabBits_Website#159

Revert "Added preloader page issue-155"

---

client/public/robots.txt
client/public/sitemap.xml

Closes: #175 
Added a sitemap.xml file in the website and also added the info in the robots.txt file. This will improve the SEO performance of the website.

Added the sitemap to the website

---

client/src/components/Opportunities/Opportunities.jsx

Closes: #171 
https://github.com/GrabBits/GrabBits_Website/assets/114489502/2b267bfc-4fcf-43f9-b6c3-41548a4a2db3

Resolved search bug

---

client/src/components/Navbar/Navbar.module.css

- I made the navbar sticky 
- I defined media query (min-width=801px) so that navbar is sticky for desktop screen because in mobile view navbar is positioned bottom:0
- [ x] My code adheres to the established style guidelines of this project.
- [ x] I have conducted a self-review of my code.
- [x ] I have included comments in areas that may be difficult to understand.
- [x ] My changes have not introduced any new warnings.
https://github.com/GrabBits/GrabBits_Website/assets/101205226/25338276-1638-4ea9-ae81-df047f76181d

Made the navbar sticky

---

client/src/components/Opportunities/Opportunities.jsx
client/src/components/Opportunities/Opportunities.module.css
client/src/components/Opportunities/PreLoader/PreLoader.jsx
client/src/components/Opportunities/PreLoader/PreLoader.module.css
client/src/components/common/Loader/Loader.jsx
client/src/components/common/Loader/Loader.module.css

Closes: #154 
- Added a cool animation loader on opportunities page using Vanilla CSS.
- `client/src/components/Opportunities/Opportunities.jsx`
- `client/src/components/Opportunities/Opportunities.module.css`
- `client/src/components/common/Loader/Loader.jsx`
- `client/src/components/common/Loader/Loader.module.css`
[Grab-Bits.webm](https://github.com/GrabBits/GrabBits_Website/assets/130365071/430b9508-5e7d-431e-922d-09f2a7e5e12f)

feat: improve loader on opportunities page

---

client/src/components/Navbar/Navbar.jsx
client/src/components/Navbar/Navbar.module.css

close navbar on click and repositioned the close button

---

client/src/components/Testimonials/Card.module.css
client/src/components/Testimonials/TeamPostCard.jsx

Made fixes in testimonial section and made navigation buttons working

---

client/src/components/Navbar/Navbar.jsx
client/src/components/Navbar/Navbar.module.css

fixed issue of navbar logo

---

client/src/components/Extra/Extra.jsx
client/src/components/Extra/Extra.module.css

Made Changes In Homepage incliuding extra component and fixes

---

client/.env
client/src/components/Resources/Resources.jsx

added books
